---
#- name: Add nginx repo
#  yum_repository:
#    baseurl: http://nginx.org/packages/mainline/rhel/7/$basearch/
#    enabled: true
#    gpgcheck: false
#    description: Nginx repo
#    name: nginx

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start and enable Nginx
  service:
    name: nginx
    enabled: true
    state: started

- name: Add Nginx config
  template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default #/etc/nginx/conf.d/default.conf
    mode: 0644

- name: Restart nginx
  service:
    name: nginx
    enabled: true
    state: restarted